# This is an example of PolicyBinding that specifies an SLOHorizontalScale
# policy and the target services that the policy applies to
apiVersion: policy.turbonomic.io/v1alpha1
kind: PolicyBinding
metadata:
  name: policy-binding-sample
spec:
  # The reference to the SLOHorizontalScale policy
  policyRef:
    kind: SLOHorizontalScale
    name: slo-horizontal-scale-sample
  # The target services that the policy applies to
  targets:
    - apiVersion: apps/v1
      kind: Service
      name: twitter-cass-api
    - apiVersion: apps/v1
      kind: Service
      name: twitter-cass-(tweet|user)